// Package event defines the Cadence Event Contract in Go.
//
// This is THE frozen contract (see docs/00-SYSTEM-KNOWLEDGE.md §5) that every
// collector and the backend share. The JSON shape produced here is the artifact
// the Wave-1 streams (P1-B vscode, P1-C chrome, P1-D dashboard) depend on, so it
// must not drift. Changing the wire shape or bumping SchemaVersion is a
// coordination event: update §5 first, then this file.
//
// Contract invariants enforced here:
//   - Every field key is ALWAYS present on the wire. A collector that cannot
//     fill a value sends JSON null, never omits the key. We therefore use no
//     `omitempty`, and nullable fields are pointers so absence marshals to null.
//   - `meta` is additive forever: unknown keys are preserved on round-trip and
//     never rejected. It is modelled as a map so future keys cost nothing.
//   - Timestamps are UTC RFC3339; storage never localizes.
package event

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// SchemaVersion is the current Event Contract version. Bump ONLY via a
// coordination event (see §5). Collectors stamp this into every event.
const SchemaVersion = 1

// Source identifies which collector produced an event.
type Source string

const (
	SourceOS     Source = "os"     // OS active-window + idle collector
	SourceVSCode Source = "vscode" // VSCode extension
	SourceChrome Source = "chrome" // Chrome extension
	SourceToken  Source = "token"  // AI coding-agent token watcher
	SourceGitHub Source = "github" // GitHub poller
)

// AllSources lists every valid source, in contract order.
func AllSources() []Source {
	return []Source{SourceOS, SourceVSCode, SourceChrome, SourceToken, SourceGitHub}
}

// IsValid reports whether s is a recognized source.
func (s Source) IsValid() bool {
	switch s {
	case SourceOS, SourceVSCode, SourceChrome, SourceToken, SourceGitHub:
		return true
	default:
		return false
	}
}

// Category is the semantic label applied to an event by the rule classifier.
// It is nullable on the wire: pre-classification events carry null.
type Category string

const (
	CategoryDeepWork   Category = "deep_work"
	CategoryMeetings   Category = "meetings"
	CategoryComms      Category = "comms"
	CategoryResearch   Category = "research"
	CategoryCodeReview Category = "code_review"
	CategoryAIAssisted Category = "ai_assisted"
	CategoryIdle       Category = "idle"
	CategoryOther      Category = "other"
)

// AllCategories lists every valid category, in contract order.
func AllCategories() []Category {
	return []Category{
		CategoryDeepWork, CategoryMeetings, CategoryComms, CategoryResearch,
		CategoryCodeReview, CategoryAIAssisted, CategoryIdle, CategoryOther,
	}
}

// IsValid reports whether c is a recognized category.
func (c Category) IsValid() bool {
	switch c {
	case CategoryDeepWork, CategoryMeetings, CategoryComms, CategoryResearch,
		CategoryCodeReview, CategoryAIAssisted, CategoryIdle, CategoryOther:
		return true
	default:
		return false
	}
}

// Meta carries source-specific, additive-only fields. Unknown keys are ignored,
// never rejected, and survive a marshal/unmarshal round-trip. Well-known keys
// are listed below as constants for type-safe access by collectors.
type Meta map[string]any

// Well-known meta keys (see §5). These are conventions, not a closed set —
// collectors may add new keys at any time without a contract change.
const (
	MetaLang      = "lang"       // vscode: source language, e.g. "typescript"
	MetaModel     = "model"      // token: model id, e.g. "claude-sonnet-4"
	MetaTokensIn  = "tokens_in"  // token: input token count
	MetaTokensOut = "tokens_out" // token: output token count
	MetaCostUSD   = "cost_usd"   // token: cost in USD
	MetaCommitSHA = "commit_sha" // github: commit sha
	MetaRepo      = "repo"       // github: "org/repo"
)

// Event is one atomic activity record. Field order matches the wire order in
// §5; the JSON tags are the frozen contract.
type Event struct {
	EventID    string    `json:"event_id"`    // uuid-v4, generated by the collector
	SchemaVer  int       `json:"schema_ver"`  // == SchemaVersion
	Source     Source    `json:"source"`      // os | vscode | chrome | token | github
	MemberID   string    `json:"member_id"`   // local member identity
	TsStart    time.Time `json:"ts_start"`    // RFC3339 UTC
	TsEnd      time.Time `json:"ts_end"`      // RFC3339 UTC
	DurationMs int64     `json:"duration_ms"` // ts_end - ts_start, precomputed
	App        string    `json:"app"`         // human-readable app name
	Title      *string   `json:"title"`       // window/tab title; null if unavailable/redacted-out
	URL        *string   `json:"url"`         // chrome only; null otherwise
	Project    *string   `json:"project"`     // best-effort project/repo; nullable
	Category   *Category `json:"category"`    // set by classifier; null pre-classify
	IsIdle     bool      `json:"is_idle"`     // true if no input during the window
	Meta       Meta      `json:"meta"`        // source-specific, additive
}

// MarshalJSON guarantees `meta` is always emitted as an object (never null),
// honoring the "every key always present" contract rule even for a nil map.
func (e Event) MarshalJSON() ([]byte, error) {
	type wire Event // alias avoids infinite recursion
	w := wire(e)
	if w.Meta == nil {
		w.Meta = Meta{}
	}
	return json.Marshal(w)
}

// New builds an event with the schema version stamped, timestamps normalized to
// UTC, duration_ms precomputed, a fresh uuid-v4 id, and a non-nil meta map.
// Nullable fields (title, url, project, category) start as null; set them via
// the Ptr helpers as needed.
func New(src Source, memberID string, tsStart, tsEnd time.Time, app string) (*Event, error) {
	id, err := NewID()
	if err != nil {
		return nil, err
	}
	e := &Event{
		EventID:   id,
		SchemaVer: SchemaVersion,
		Source:    src,
		MemberID:  memberID,
		TsStart:   tsStart.UTC(),
		TsEnd:     tsEnd.UTC(),
		App:       app,
		Meta:      Meta{},
	}
	e.ComputeDuration()
	return e, nil
}

// ComputeDuration sets DurationMs from the current timestamps (truncated to
// whole milliseconds). Call after adjusting ts_start/ts_end.
func (e *Event) ComputeDuration() {
	e.DurationMs = e.TsEnd.Sub(e.TsStart).Milliseconds()
}

// Validate checks the contract invariants. It is the single gate collectors and
// the local ingest route use before persisting an event.
func (e *Event) Validate() error {
	if e.SchemaVer != SchemaVersion {
		return fmt.Errorf("event: schema_ver %d unsupported (want %d)", e.SchemaVer, SchemaVersion)
	}
	if strings.TrimSpace(e.EventID) == "" {
		return fmt.Errorf("event: event_id is required")
	}
	if !e.Source.IsValid() {
		return fmt.Errorf("event: source %q is not a valid source", e.Source)
	}
	if strings.TrimSpace(e.MemberID) == "" {
		return fmt.Errorf("event: member_id is required")
	}
	if e.TsStart.IsZero() || e.TsEnd.IsZero() {
		return fmt.Errorf("event: ts_start and ts_end are required")
	}
	if e.TsEnd.Before(e.TsStart) {
		return fmt.Errorf("event: ts_end %s is before ts_start %s",
			e.TsEnd.Format(time.RFC3339), e.TsStart.Format(time.RFC3339))
	}
	if want := e.TsEnd.Sub(e.TsStart).Milliseconds(); e.DurationMs != want {
		return fmt.Errorf("event: duration_ms %d does not match ts_end-ts_start %d", e.DurationMs, want)
	}
	if e.App == "" {
		return fmt.Errorf("event: app is required")
	}
	if e.Category != nil && !e.Category.IsValid() {
		return fmt.Errorf("event: category %q is not a valid category", *e.Category)
	}
	return nil
}

// NewID returns a random RFC 4122 version-4 UUID string. No external deps.
func NewID() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("event: generate uuid: %w", err)
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16]), nil
}

// Ptr returns a pointer to v. Useful for setting nullable fields, e.g.
// e.Title = event.Ptr("auth.ts — cadence-api").
func Ptr[T any](v T) *T { return &v }
